apiVersion: v1
kind: Service
metadata:
  name: ajktown-golf-svc
  namespace: ajktown
  labels:
    app: ajktown-golf
spec:
  selector:
    app: ajktown-golf
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: NodePort