name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ajktown
        password: ${{ secrets.AJKTOWN_ORG_ACTION }}

    - name: Build and push for PR
      if: github.event_name == 'pull_request'
      uses: docker/build-push-action@v6
      with:
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ajktown/golf:pr${{ github.event.pull_request.number }}

    - name: Build the Docker image as latest
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: docker buildx build --file Dockerfile --platform linux/arm64,linux/amd64 --tag ajktown/golf:latest .

    - name: Push the Docker image as latest
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: docker push ajktown/golf:latest
